version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: nanophate/circleci-runner
    parallelism: 3 
    steps:
      - checkout
      - run: echo "hello naa"
      - run: sleep 500
      - run:
          name: Check CircleCI Files
          command:  ls -la /home/circleci/
          when: always

workflows:
  workflow:
    jobs:
      - build
# VS Code Extension Version: 1.2.1
