version: 2.1
jobs:
  build:
    machine: true
    resource_class: nanophate/220713-cci0macbook
    steps:
      - checkout
      - run: echo "hello naa"
      - run: sleep 500
      - run:
          name: Check CircleCI Files
          command:  ls -la /home/circleci/
          when: always

workflows:
  workflow:
    jobs:
      - build
# VS Code Extension Version: 1.2.1
